services:
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - dev-network
  product-api:
    image: fernandocanabarroahnert/express-typescript-ecommerce
    container_name: product-api
    environment:
      - DATABASE_URL=postgresql://postgres:1234567@pg-docker:5432/products
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=secret-key
      - ACCESS_TOKEN_DURATION=86400
      - REFRESH_TOKEN_DURATION=2592000
      - PORT=3000
      - NODE_ENV=dev
      - LOG_LEVEL=http
    ports:
      - "3000:3000"
    depends_on:
      - pg-docker
      - redis
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: