name: Continuous Integration/Continuous Delivery (CI/CD) with Github Actions

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ACCESS_TOKEN_DURATION: "86400"
          REFRESH_TOKEN_DURATION: "604800"
          PORT: "3000"
          NODE_ENV: "test"
          LOG_LEVEL: "info"
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm run test

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build Project
              run: npm run build
              
            - name: Build Docker Image
              uses: docker/build-push-action@v2
              with:
                context: .
                dockerfile: Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKER_HUB_USERNAME }}/express-typescript-ecommerce:latest
                    ${{ secrets.DOCKER_HUB_USERNAME }}/express-typescript-ecommerce:${{ github.run_id }}